# Generated by Django 5.1.2 on 2024-11-30 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Special Categories',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='PrimaryCategory',
        ),
        migrations.AlterModelOptions(
            name='primarycategory',
            options={'verbose_name_plural': 'Primary Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.primarycategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.specialcategory'),
        ),
    ]
