# Generated by Django 5.1.2 on 2024-11-30 12:33

import django.db.models.deletion
from django.db import migrations, models


def set_default_category(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    default_category = apps.get_model('products', 'PrimaryCategory').objects.get(id=1)  # Replace with your default category ID
    Product.objects.filter(primary_category__isnull=True).update(primary_category=default_category)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_specialcategory_rename_category_primarycategory_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_category),
    ]
