# Generated by Django 5.1.2 on 2024-12-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_stock_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_amount',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
